[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend/api && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "3001" }
NODE_ENV = { default = "production" }